config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from mysite import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls')),
]  
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

mysite/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from mysite import views

app_name = 'mysite'

urlpatterns = [
    path('', views.base1, name='base1'), 
    path('file_upload/', views.new_post, name="new_post"),
    path('recommand/', views.food_list, name="food_list"),
    path('recommand1/', views.food_list1, name="food_list1"),
    path('map/', views.map, name='map'),
    path('blank/', views.molar, name='molar'),
    
    #메뉴
    path('map/', views.map, name='map'),
    path('map/gotowork', views.gotowork, name='gotowork'),
    path('map/gunae', views.gunae, name='gunae'),
    path('map/rol', views.rol, name='rol'),
    path('map/dol', views.dol, name='dol'),
    path('map/lee', views.lee, name='lee'),
    path('map/mak', views.mak, name='mak'),
    path('map/mij', views.mij, name='mij'),
    path('map/bac1', views.bac1, name='bac1'),
    path('map/bac2', views.bac2, name='bac2'),
    path('map/bac3', views.bac3, name='bac3'),
    path('map/bon', views.bon, name='bon'),
    path('map/bun', views.bun, name='bun'),
    path('map/bac4', views.bac4, name='bac4'),
    path('map/bac5', views.bac5, name='bac5'),
    path('map/sae', views.sae, name='sae'),
    path('map/sun', views.sun, name='sun'),
    path('map/yuk', views.yuk, name='yuk'),
    path('map/yeo', views.yeo, name='yeo'),
    path('map/one', views.one, name='one'),
    path('map/ins', views.ins, name='ins'),
    path('map/jes', views.jes, name='jes'),
    path('map/han', views.han, name='han'),
    path('map/hon', views.hon, name='hon'),

    
    #추천기록
    path('record', views.show_food, name='food'),
    path('fchoice/', views.fchoice, name='choice'),
    path('foodview/', views.foodview, name='final'),
    # path('predict/', views.predict_model, name='predict_model'),

] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

mysite/views.py
from django.shortcuts import render, get_object_or_404, redirect
from mysite.models import Post, resultall, fullist, choice, Comment
from django.utils import timezone
from django.db import connection
from django.urls import reverse
from django.views.generic import DeleteView
import pymysql
import random
import os
from django.contrib import messages
from django.core.paginator import Paginator  


# 딥러닝
import tensorflow
from tensorflow.keras.preprocessing import image
from tensorflow.keras import models, layers
from tensorflow.keras.models import load_model
import cv2
import numpy as np

# 날씨
import requests
import re
from bs4 import BeautifulSoup as bs
import pandas as pd

# 계절
import datetime

import glob
from PIL import Image


count = 0
rec_count = 0
def base1(request):
    global count
    count = count + 1
    return render(request, 'mysite/base1.html', {"rec_count":rec_count, "count":count})


# # Create your views here.
def index(request):
    return render(request,'mysite/index.html')


# def log(request):
    
#     #DB에서 감정, 계절 가져오기
#     cursor = connection.cursor()

#     strSql = "SELECT * FROM mysite_resultall"
#     result = cursor.execute(strSql)
#     datas = cursor.fetchall()

#     connection.commit()
#     connection.close()

#     arr = []
#     for data in datas:
#         row = {
#             'created_at' : data[5],
#             'emotion' : data[3],
#             'season' : data[4],
#         }
#         arr.append(row)

#     b = arr[-1]["emotion"]
#     c = arr[-1]["season"]

#     # 클릭하면 DB에 저장
#     if request.method == 'POST':
#         if request.POST.get('click'):
#             a1 = '파스타'
#             new_article=Log.objects.create(
#                 emotion=b,
#                 season=c,
#                 click= a1,
#             )
#         elif request.POST.get('click2'):
#             a1 = '마라탕'
#             new_article=Log.objects.create(
#                 emotion=b,
#                 season=c,
#                 click= a1,
#             )
#         elif request.POST.get('click3'):
#             a1 = '국밥'
#             new_article=Log.objects.create(
#                 emotion=b,
#                 season=c,
#                 click= a1,
#             )
        

#     return render(request,'mysite/log.html')

def foodview(request):
    page = request.GET.get('page', '1')  # 페이지
    f2 = choice.objects.all().order_by('-pk')
    paginator = Paginator(f2, 15)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'f2': page_obj}
    return render(request, 'mysite/choice.html', context)

def fchoice(request):
    fd = fullist.objects.all()
    # 전체 메뉴 조회
    global count
    count = count + 1
    f3 = []
    f1 = request.GET['choice']
    # f1.split(',')
    f3.append(f1.split(','))
    
   
    # df1 = pd.Series(f3)
    df1 =pd.DataFrame(list(f3))
    df1.reset_index
    df1 = df1.rename(columns={0:"음식명",1:"음식점",2:"감정상태", 3:"날씨",4:"계절"})
    # df1.drop([''],axis=1)
    # df1 = df1.columns["메뉴명","음식점","감정상태"]
    # df1[0] = df1[0].str.replace("0"," ", )
    # df1 =pd.DataFrame(f3).transpose()
    df1.loc[df1["음식점"]=="Back다방","음식점"] = "빽다방"
    df1.loc[df1["음식점"]=="돌배기","음식점"] = "돌배기집"
    df1.loc[df1["음식점"]=="백종원의 元祖쌈밥집","음식점"] = "원조쌈밥집"
    df1.loc[df1["음식점"]=="백철판","음식점"] = "백철판0410"
    df1.loc[df1["음식점"]=="역전우동","음식점"] = "역전우동0410"
    df1.loc[df1["음식점"]=="홍콩반점","음식점"] = "홍콩반점0410"
    df1.loc[df1["음식점"]=="빽보이","음식점"] = "빽보이피자"



    
    choice.objects.create(
        menu = str(df1["음식명"].values).replace("['","").replace("']",""),
        res = str(df1["음식점"].values).replace("['","").replace("']",""),
        emotion = str(df1["감정상태"].values).replace("['","").replace("']",""),
        weather = str(df1["날씨"].values).replace("['","").replace("']",""),
        season = str(df1["계절"].values).replace("['","").replace("']","")  
    )
 
    
    foodlist = resultall.objects.all()        

    f2 = choice.objects.all().order_by('-pk')
    choice_res = str(df1["음식점"].values).replace("['","").replace("']","")
    
    if request.method =="POST":
        res = str(df1["음식점"].values).replace("['","").replace("']","")
        if request.POST.get(f'{res}'):
            new_article=Comment.objects.create(
                고투웍= request.POST.get('고투웍'),
                구내식당= request.POST.get('구내식당'),
                돌배기집= request.POST.get('돌배기집'),
                롤링파스타= request.POST.get('롤링파스타'),
                리춘시장= request.POST.get(f'리춘시장'),
                막이오름= request.POST.get('막이오름'),
                미정국수= request.POST.get('미정국수'),
                백S비빔밥= request.POST.get('백S비빔밥'),
                백스비어= request.POST.get('백스비어'),
                백철판0410= request.POST.get('백철판0410'),
                본가= request.POST.get('본가'),
                분식9단= request.POST.get('분식9단'),
                빽다방= request.POST.get('빽다방'),
                빽보이피자= request.POST.get('빽보이피자'),
                새마을식당= request.POST.get('새마을식당'),
                성성식당= request.POST.get('성성식당'),
                역전우동0410= request.POST.get('역전우동0410'),
                연돈볼카츠= request.POST.get('연돈볼카츠'),
                원조쌈밥집 = request.POST.get('원조쌈밥집'),
                인생설렁탕= request.POST.get('인생설렁탕'),
                제순식당= request.POST.get('제순식당'),
                한신포차= request.POST.get('한신포차'),
                홍콩반점= request.POST.get('홍콩반점'),
            
            )
        else:
            new_article=Comment.objects.create(
                
            )
        f3 = Comment.objects.filter().only(f'{res}')
        
      
    return render(request, f'mysite/{choice_res}map.html', {'context':f3, 'fd':fd,'f1':f1,'f2':f2 ,'count':count, 'foodlist':foodlist})

def new_post(request):
    try:
        if request.method == 'POST':
            if request.POST.get('mainphoto'):
                new_article=Post.objects.create(
                    # postname=request.POST.get('postname'),
                    # contents=request.POST.get('contents'),
                    mainphoto= request.FILES['mainphoto'],
                )
            else:
                new_article=Post.objects.create(
                    # postname=request.POST.get('postname'),
                    # contents=request.POST.get('contents'),
                    mainphoto= request.FILES['mainphoto'],
                )

                cursor = connection.cursor()

                strSql = "SELECT * FROM mysite_post"
                result = cursor.execute(strSql)
                datas = cursor.fetchall()

                connection.commit()
                connection.close()

                arr = []
                for data in datas:
                    row = {
                        'mainphoto' : data[1]
                    }
                    arr.append(row)  

                ptlink = arr[-1]["mainphoto"]
                
                files = glob.glob(f'C:/temp/web_study/media/{ptlink}')
                for f in files:
                    title, ext = os.path.splitext(f)
                    if ext in ['.jpg', '.png']:
                        img = Image.open(f)
                        img_resize = img.resize((250, 250))
                        img_resize.save(title + ext)
            return redirect('/recommand/')
    except:
        return redirect('/file_upload/')
    return render(request, 'mysite/new_post.html' ,{"rec_count":rec_count, "count":count})

def show_post(request):
    #최신순으로 조회(-pk 역순 조회)
    postlist = Post.objects.all().order_by('-pk')
    return render(request, 'mysite/show.html', {'postlist':postlist})
#끝

#음식기록 추가코드(show_food 페이지와 연결)
def show_food(request):
    

    return render(request, 'mysite/foodlist.html')



def molar(request): #버튼 POST이었을 때 
    if request.method == 'POST':
        if request.POST.get('angry'):
            a1 = 'angry'
        elif request.POST.get('happy'):
            a1 = 'happy'
        else:
            a1 = 'sad'
        
    return render(request, 'mysite/food_list1.html',{"rec_count":rec_count, "count":count})


def food_list1(request):
    if request.method == 'POST':
        if request.POST.get('angry'):
            a1 = 'angry'
            emotion = '분노한'
        elif request.POST.get('happy'):
            a1 = 'happy'
            emotion = '기쁜'
        else:
            a1 = 'sad'
            emotion = '슬픈'

    cursor = connection.cursor()

    strSql = "SELECT * FROM mysite_post"
    result = cursor.execute(strSql)
    datas = cursor.fetchall()

    connection.commit()
    connection.close()


    arr = []
    for data in datas:
        row = {
            'id' : data[0],
            'mainphoto' : data[1]
        }
        arr.append(row)  

    ptlink = arr[-1]["mainphoto"]
    
    model = load_model('C:/Program Files/VGG16_BatchNor.h5') # 모델명
    
    roi = cv2.imread('media/{}'.format(ptlink)) # 파일 경로
    #roi = cv2.imread('media/{}'.format(arr[-1].mainphoto)) # 파일 경로
    
    # w, h = 250, 250
    # roi = cv2.resize(roi, (w,h), interpolation = cv2.INTER_AREA)
    roi = roi.astype('float') / 255.0
    # roi = img_to_array(roi)
    roi = np.expand_dims(roi, axis=0)
    # img = img.reshape(1,w,h,3)

    Prediction = model.predict(roi)

    #Prediction[0]   #감정별 백분율 (화남 0, 기쁨 1, 중립 2, 슬픔3)


    # percent = Prediction[0][np.argmax(Prediction)]

    result = np.argmax(Prediction)#백분율이 제일 높은 값

    global rec_count
    rec_count = rec_count + 1
    

    html = requests.get('https://weather.naver.com/today/09680630?cpName=KMA')
    soup = bs(html.text, 'html.parser') 

    
    data1 = soup.find('span', {'class':'weather'}).get_text()
    if data1 == '비':
        b = '_rain'
        wea = "비가 오는 바깥의"
        wea1 = "비"
    elif data1 == '눈':
        b = '_snow'
        wea = "눈이 오는 바깥의"
        wea1 = "눈"
    else:
        b = ''
        wea = data1
        
    
    now = datetime.datetime.now()
    if now.month == [3, 4, 5]:
        c = '_spring'
        season = "봄"
    elif now.month == [6, 7, 8]:
        c = '_summer'
        season = "여름"

templates/mysite/blog.html
    
    <!-- 게시판(postlist)의 게시글(list)을 하나씩 보여줍니다 -->
    <!-- {와 %로 이루어진 구문 내부엔 파이썬이 사용됩니다 -->
    <!-- <table>
        {% for list in postlist %}
        <!-- 게시글 클릭시 세부페이지로 넘어갑니다-->
        <!-- <ul>
            <li><a href="{{list.pk}}/">{{list.postname}}</a></li>
        </ul>
        {% endfor %}
    </table> -->
    <!-- <button><a href="new_post/">글쓰기</a></button> -->
    표정을 통한 음식 추천
    <br>
    <a href="{% url 'mysite:agree' %}">시작하기</a>

templates/mysite/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>
    장고 첫페이지!
</body>

</html>

templates/mysite/log.html
ㅎㅇ
{{log}} <br>
(시간) (감정_계절_날씨) 일때 (음식점_메뉴)를 클릭하셨습니다. 

<br>{{arr}}
<br>{{a}}
<br>{{b}}
<br>{{c}}
<br>{{a1}}
<br>sdf
<br>{{arr.created_at}}
<br>{{arr.emotion}}
<br>{{arr.season}}



<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div style="width: 100%; text-align : center;">
        <div style="display: inline-block;"><button type="submit" name="click" class="btn-recommend" value="글쓰기">롤링파스타</button></div>
                    
    </div>
    <div style="width: 100%; text-align : center;">
        <div style="display: inline-block;"><button type="submit" name="click2" class="btn-recommend" value="글쓰기">성성식당</button></div>
    
    </div>
    <div style="width: 100%; text-align : center;">
        <div style="display: inline-block;"><button type="submit" name="click3" class="btn-recommend" value="글쓰기">홍콩반점</button></div>
    
    </div>

</form>

templates/mysite/구내식당map.html
<!-- 추가 -->
{% load static %}
<!-- 추가끝 -->

<!DOCTYPE html>
<html>
<head>
    
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />

        <!-- 추가 -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="{% static 'img/main_icon10.png' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/10000hours.css' %}">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script defer src="{% static 'js/10000hours.js' %}"></script>
        <title>매장정보보기</title>
        <!-- 추가끝 -->
    
        <script>
            L_NO_TOUCH = false;
            L_DISABLE_3D = false;
        </script>

    <style>
        html,
        body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
        }
    </style>
    <style>
        #map {
            position: absolute;
            top: 0;
            bottom: 0;
            right: 0;
            left: 0;
        }
/* 추가 */
        hr {
            height: 1px;
            background-color: black !important;
            border-color: black !important;
            color :black !important;
        }

        .count {
            font-family: 'GmarketSansMedium'!important;
            font-size: 16px !important;
            background-color: rgb(255, 255, 255) !important;
            color: rgb(0, 0, 0) !important;
        }
/* 추가끝 */

    </style>
    
    <script src="https://cdn.jsdelivr.net/npm/leaflet@1.6.0/dist/leaflet.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.6.0/dist/leaflet.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/python-visualization/folium/folium/templates/leaflet.awesome.rotate.min.css"/>
    
            <meta name="viewport" content="width=device-width,
                initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
            <style>
                #map_681af8511c01f63fda062e894ee92f91 {

                    /* 변경 */
                    text-align: center;
                    position: relative;
                    width: 70%;
                    height: 700px;
                    left: 0.0%;
                    top: 0.0%;
                    margin-left: 15%;
                    margin-right: 15%;
                    /* 변경끝 */
                }
            </style>
        
</head>
<body>
        <!-- 추가 -->
        <div>
    
            <div style="margin-left: 75px; margin-right: 75px; margin-top: 10px; margin-bottom: 0px; width: 90%;">
                <a href="{% url 'mysite:base1' %}"><img src="{% static 'img/top10.png' %}" alt="홈페이지로고" width="100%" height="200" title="홈페이지로고"></a>
            </div>
    
            </div>
            <div style="text-align : center ;margin-bottom: 0px; margin-top: 0px;">
            <ul class="nav-container" style="text-align : center;">
                <li class="nav-item"><a href="{% url 'mysite:base1' %}">
                        <font size="4em" color="white">HOME</font>
                    </a></li>
                <li class="nav-item"><a href="{% url 'mysite:final' %}">
                        <font size="4em" color="white">선택기록보기</font>
                    </a></li>
                <li class="nav-item"><a href="{% url 'mysite:map' %}">
                        <font size="4em" color="white">매장정보보기</font>
                    </a></li>
                <li class="nav-item"><a href="{% url 'mysite:new_post' %}">
                        <font size="4em" color="white">메뉴추천받기</font>
                    </a></li>
                <li class="nav-item"><label for="before">
                        <font size="4em" color="white">이전페이지</font>
                    </label><input type="button" id="before" style="display:none; visiblity:hidden ;" onclick="history_back()"></li>
            </ul>
                </div>
                
                <script>
                    function history_back() {
                        history.back();
                    }
                </script>
    
        <div style="text-align : center; margin-bottom: 80px; margin-top: 80px;">
            <b><font size="12em" color="red">구내식당</font><font size="10em" color="black"> 지도보기 </font></b>
        </div>
    
        <!-- 안내문 영역 -->
        <!-- <div style="text-align : center; margin-bottom: 40px;">
            <font size="5em" color="black"><b>지도 위 핀을 클릭하면<br><br>지점 주소, 전화번호, 운영시간 등 <br><br>다양한 정보 확인이 가능합니다</b></font>
        </div> -->
        <div style="text-align : center; margin-bottom: 20px;">
            <font size="3em" color="black"><b>지도 위 핀을 클릭하면 지점 주소, 전화번호, 운영시간 등 다양한 정보 확인이 가능합니다</b></font>
        </div>
        <!-- 추가끝 -->
    
    
            <div class="folium-map" id="map_681af8511c01f63fda062e894ee92f91" ></div>
        <div class="container my-3">
        
            <form method="POST" class="form my-3" enctype="multipart/form-data">
                {%csrf_token%}
                <div class="form-group">
                    <h1 for="content">댓글등록하기</h1>
                    <textarea class="form-control" type="text" name="구내식당" id="content" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">저장하기</button>
            </form>
        </div>
        <p>
        
            {%for comment in context %}
            {% if comment.구내식당 != null %}
        <div class="container my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">{{comment.구내식당}}</div>
                <div class="d-flex justify-content-end">
                    <div class="badge bg-light text-dark p-2">
                        {{comment.created_date}}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {%endfor%}
        <!-- 추가 -->
            <div class = "count" style="margin-top: 250px;">
                <div style="display: inline-block; margin-left: 100px;">누적 방문자수 : {{count}}명</div>
                <div style="display: inline-block; margin-left: 50px;">누적 추천횟수 : {{rec_count}}회</div>
            </div>
          
            <br>
            <div >
            <hr size="3px" width="90%">
            <section id="copyright">
                
                <p>
                    ※ 본 서비스의 저작권은 멀티캠퍼스 데이터사이언스/엔지니어링 3팀 식스시그마에 있습니다.<br>
                    수정 및 재배포, 무단 도용 시 법적인 문제가 발생할 수 있습니다.
                </p>
            </section>
            </div>
            <!-- 추가끝 -->
</body>
<script>
    
    
            var map_681af8511c01f63fda062e894ee92f91 = L.map(
                "map_681af8511c01f63fda062e894ee92f91",
                {
                    center: [37.559819, 126.963895],
                    crs: L.CRS.EPSG3857,
                    zoom: 11,
                    zoomControl: true,
                    preferCanvas: false,
                }
            );

            

        
    
            var tile_layer_da717a93fdeada432354fb2a6e98e033 = L.tileLayer(
                "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                {"attribution": "Data by \u0026copy; \u003ca href=\"http://openstreetmap.org\"\u003eOpenStreetMap\u003c/a\u003e, under \u003ca href=\"http://www.openstreetmap.org/copyright\"\u003eODbL\u003c/a\u003e.", "detectRetina": false, "maxNativeZoom": 18, "maxZoom": 18, "minZoom": 0, "noWrap": false, "opacity": 1, "subdomains": "abc", "tms": false}
            ).addTo(map_681af8511c01f63fda062e894ee92f91);
        
    
            var marker_38bb565bb898be8b5563515d6cb21271 = L.marker(
                [37.5070967, 127.0242744],
                {}
            ).addTo(map_681af8511c01f63fda062e894ee92f91);
        
    
            var icon_49537c4b990e646ed0b702e66c940d8a = L.AwesomeMarkers.icon(
                {"extraClasses": "fa-rotate-0", "icon": "star", "iconColor": "white", "markerColor": "red", "prefix": "glyphicon"}
            );
            marker_38bb565bb898be8b5563515d6cb21271.setIcon(icon_49537c4b990e646ed0b702e66c940d8a);
        
    
        var popup_4b50b714caff5de988248ecd5d131fe2 = L.popup({"maxHeight": 1000, "maxWidth": 1500, "minHeight": 700, "minWidth": 400, "src": "0.0"});

        
            
                var i_frame_809210f947c68e03c56082d7db8522a2 = $(`<div style="width:100%;"><div style="position:relative;width:100%;height:0;padding-bottom:60%;"><iframe src="data:text/html;charset=utf-8;base64,CiAgICA8aDI+6rWs64K07Iud64u5IOuFvO2YhOuzuOygkDxicj48aDQ+PGI+7KCE7ZmU67KI7Zi4PC9iPiA6IDAyLTM0NDUtNzU4OTxicj48YnI+PGI+7KeA7KCQ7KO87IaMPC9iPiA6IOyEnOyauCDqsJXrgqjqtawg64W87ZiE64+ZIDE2Ny0zMTxicj48YnI+PGI+7JiB7JeF7Iuc6rCEPC9iPiA6IDI07Iuc6rCEIDxicj48YnI+PGltZyBzcmMgPSAnMC4wJ3dpZHRoPSczMDAnIGhlaWdodD0nMjAwJz4=" style="position:absolute;width:100%;height:100%;left:0;top:0;border:none !important;"></iframe></div></div>`)[0];
                popup_4b50b714caff5de988248ecd5d131fe2.setContent(i_frame_809210f947c68e03c56082d7db8522a2);
            
        

        marker_38bb565bb898be8b5563515d6cb21271.bindPopup(popup_4b50b714caff5de988248ecd5d131fe2)
        ;

        
    
    
            marker_38bb565bb898be8b5563515d6cb21271.bindTooltip(
                `<div>
                     논현본점
                 </div>`,
                {"sticky": true}
            );
        
</script>
</html>